[workspace]
channels = ["conda-forge"]
name = "NSBI-workflow-tutorial"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
cabinetry = ">=0.6.0,<0.7"
ipykernel = ">=6.30.1,<7"

[feature.gpu.system-requirements]
cuda = "12.5"

[feature.gpu.dependencies]
python = ">=3.12.11,<3.13"
pip = ">=25.2,<26"
jax = ">=0.4.31,<0.5"
tf2onnx = ">=1.16.1,<2"
scikit-learn = ">=1.7.1,<2"
pytables = ">=3.10.2,<4"
matplotlib-base = ">=3.10.5,<4"
mplhep = ">=0.4.1,<0.5"
numpy = ">=1.26.4,<2"
scipy = ">=1.16.1,<2"
pandas = ">=2.3.2,<3"
awkward = ">=2.8.7,<3"
pixi-kernel = ">=0.6.6,<0.7"
tensorflow-gpu = "2.17.*"
cuda-version = "12.5.*"
cudnn = "8.9.*"
onnxruntime = "1.18.*"
uproot = ">=5.6.4,<6"
coffea = ">=2025.7.3,<2026"
awkward-pandas = ">=2023.8.0,<2024"

[feature.gpu.pypi-dependencies]
nsbi-common-utils = { path = ".", editable = true }
higgsml = "==0.1.3"

[environments]
nsbi-env-gpu = { features = ["gpu"], no-default-feature = true }
