General:
      Measurement    : 
              Name : higgs_tautau_signal_strength
              ParametersToFit  : 
                              - mu_htautau
                              - mu_ztautau
                              - mu_ttbar
                              - TES
                              - JES
              POI  : mu_htautau

Samples:
    - Name              : htautau
      Tree              : tree_htautau
      SamplePath        : saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : True
      UseAsBasis        : True

    - Name              : ttbar
      Tree              : tree_ttbar
      SamplePath        : saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : True
      UseAsBasis        : True
        
    - Name : ztautau
      Tree              : tree_ztautau
      SamplePath        : saved_datasets/dataset_nominal.root
      Weight            : weights
      UseAsReference    : False
      UseAsBasis        : True

NormFactors:
  - Name: "mu_htautau"
    Samples: "htautau"
    Nominal: 1
    Bounds: [0, 10]
  - Name: "mu_ztautau"
    Samples: "ztautau"
    Nominal: 1
    Bounds: [0, 10]
  - Name: "mu_ttbar"
    Samples: "ttbar"
    Nominal: 1
    Bounds: [0, 10]
    
Systematics:
    -   Name                : JES
        Type                : NormPlusShape
        Nominal             : 0
        Samples             : 
              - htautau
              - ztautau
              - ttbar
        Up                  : 
            -   SampleName        : htautau
                Path              : saved_datasets/dataset_JES_up.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : saved_datasets/dataset_JES_up.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : saved_datasets/dataset_JES_up.root
                Tree              : tree_ttbar
                Weight            : weights
        Dn                  :
            -   SampleName        : htautau
                Path              : saved_datasets/dataset_JES_dn.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : saved_datasets/dataset_JES_dn.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : saved_datasets/dataset_JES_dn.root
                Tree              : tree_ttbar
                Weight            : weights
    -   Name                : TES
        Type                : NormPlusShape
        Nominal             : 0
        Samples             : 
              - htautau
              - ztautau
              - ttbar
        Up                  :
            -   SampleName        : htautau
                Path              : saved_datasets/dataset_TES_up.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : saved_datasets/dataset_TES_up.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : saved_datasets/dataset_TES_up.root
                Tree              : tree_ttbar
                Weight            : weights
        Dn                  :
            -   SampleName        : htautau
                Path              : saved_datasets/dataset_TES_dn.root
                Tree              : tree_htautau
                Weight            : weights
            -   SampleName        : ztautau
                Path              : saved_datasets/dataset_TES_dn.root
                Tree              : tree_ztautau
                Weight            : weights
            -   SampleName        : ttbar
                Path              : saved_datasets/dataset_TES_dn.root
                Tree              : tree_ttbar
                Weight            : weights


TrainingFeatures:
    - DER_mass_transverse_met_lep
    - log_DER_mass_vis
    - log_DER_pt_h
    - DER_deltar_had_lep
    - log_DER_pt_tot
    - log_DER_sum_pt
    - DER_pt_ratio_lep_had
    - DER_met_phi_centrality
    
TrainingFeaturesToStandardize:
    - DER_mass_transverse_met_lep
    - log_DER_mass_vis
    - log_DER_pt_h
    - DER_deltar_had_lep
    - log_DER_pt_tot
    - log_DER_sum_pt
    - DER_pt_ratio_lep_had
    - DER_met_phi_centrality

Regions:
-   Name: CR
    Filter: presel_score<-1.0
    Variable: presel_score
    Type: binned
    Binning:
        - -8.747320175170898
        - -6.810490310192108
        - -4.873660445213318
        - -2.9368305802345276
        - -1.0000007152557373
-   Name: SR_binned
    Filter: presel_score>3.75
    Variable: presel_score
    Type: binned
    Binning:
        - 3.75
        - 5.942246437072754
-   Name: SR
    Filter: presel_score>=-1.0 & presel_score<=3.75
    Variable: presel_score
    Type: binned
    Binning:
        - -1.0
        - -0.5
        - 0.0
        - 0.5
        - 1.0
        - 1.25
        - 1.5
        - 1.75
        - 2.0
        - 2.25
        - 2.5
        - 2.75
        - 3.0
        - 3.25
        - 3.5
        - 3.75
